-- NOTE:
-- This migration was generated before the table creation migration
-- (20260210130000_add_task_history). Running ALTER TABLE here fails on a
-- fresh database because "task_history" does not exist yet.
--
-- Keep this migration as a no-op so migrate reset/dev can proceed safely.
